### PR TITLE
Hbrs changes

### PR DESCRIPTION
**Pull request by ifrh**
Okay I am unsure how to give you our Praktomat modification ... 
A pull request seems to be the best way ... 

This is my first pull request, so if you reject ist, please let me know 
how I could send out additions to you. 

I don't have figured how to leave some of our "HBRS-specific" modifications,
which are atleast incompatible with your "KIT-specific"  values, out of this pullrequest.

Here I list files with changes whose should perhaps not be in the master branch or handels more flexible:
- `docker-image/Dockerfile` (I commented out Isabelle support, but putting additional tools into Docker)
- `src/accounts/admin.py` **and** `src/templates/admin/accounts/user/change_list.html
  `  (We are using LDAP for user import, so commenting out a line there and add one line)
- `src/templates/attestation/rating_export.csv` (we are not using MatrikelNr but LDAP-UserIDs)
- `src/checker/checker/__init__.py` (we have deactivated some checkers)
- `src/checker/compiler/__init__.py` (we have deactivated some checkers)
- `src/checker/migrations/0003_merge-hbrs.py`  (here Tables for AutoAttestChecker, 
  DiffChecker  are generated, but at the same time Tables for not used Checkers got removed)
- `src/checker/scripts/java`  (having out commented lines), 
- `src/checker/scripts/java.policy`   **and**  `src/checker/scripts/junit.policy`   (we are doing some tests using reflections,  and redirecting console Output from students java-solutions;  therefor the policy is not 
  as hard as before )
-  `src/checker/scripts/javac` (forcing to be Java 1.8)
-  `src/checker/scripts/junit.policy.old`  **and** `src/checker/scripts/junit.policy.old2` (they shouldn't be in repository ... why they got traked?)
- `src/settings/devel.py` **and** `src/settings/local.py` (are realy HBRS specific, but they show how 
  LDAP support gets configured. Contain more comments which was useful to me: 
  Not exactly Literated Programming but likely )

This files contains bug-fixes and introduce new features:
-  `src/urls.py` solving a http 404 error (favicon.ico)
- `src/settings/defaults.py` (small fix in class D, to beable to create a SECRET_KEY file  automatical if it is missing; Introduces boolean Variables for allowing  Account changes, showing contact link and creating dummy  matrikelnumbers )
- `src/templates/tasks/task_list.html` (respect boolean show or dont show contact link)
- `src/settings/test.py`  (fix for orthografy error)
- `src/solutions/models.py`   (our handling for bug https://github.com/KITPraktomatTeam/Praktomat/issues/232#issue-153414782)
- `src/solutions/templatetags/tasks_extras.py` (An own template filter just for debugging a special value, not used at the moment)
- `src/solutions/views.py` **and**  `src/tasks/views.py`  **and**  `src/tasks/models.py` **and** `src/tasks/admin.py` **and**  `src/tasks/migrations/0002_merge-hbrs.py` **and** `src/tasks/migrations/0003_hbrs_submission_limits.py` _and_ `src/tasks/migrations/0004_merge_hbrs_jplag.py`  
  **and** `src/templates/admin/tasks/task/change_form.html`  **and**  `src/templates/attestation/attestation_view.html` **and** `src/templates/solutions/solution_detail.html` **and**  `src/templates/solutions/solution_list.html` **and** `src/templates/solutions/submission_final_lost_email.html` (dynamic waiting time, number of max student uploads, Admin action: after changing Task-Checkers while upload-time is running i.e. JUnit-Test was wrong but studentuploads realy solved,  ) 
-  `src/checker/checker/DiffChecker.py` (A script based Diff-Checker, not perfect but a little bit better than the old one from year 2013)
- `src/checker/checker/AutoAttestChecker.py` (Our AutoAttestChecker : limitation A task solution can only have 0 points or max points ... no intermediate Points are possible: we use binary points: 
  A final solution  fails after "run all checkers" => 0 points in attestation otherwise attestation has max points that is here at HBRS 1 point. "Latest of only failed" get an attestation, if Trainer choose "run all checkers of latest only failed" )
- `src/templates/admin/accounts/user/import_ldap.html` (Import user-accounts from LDAP )
  `src/templates/base.html`  **and**  `src/templates/registration/login.html` **and** `src/templates/registration/registration_change.html`  (with respect to LDAP functions)

Best regards, Robert

### CODE REVIEW

**Comment by mhecker** [comment]
Thanks for your submissions. 

Even though most changes seem sensible, i am reluctant to merge your request as-is, since it covers so many changes at once, and also, as you mentioned includes some rather "site-specific" changes.

Rather than cherry-picking those commits i "like", i may end up merging your whole request, then adding some revert-like commits on top of things i don't like. Whats  your take on this, also w.r.t. ease-of-merging on your end?

**Comment by ifrh** [comment]
Hi Martin,
It is realy okay for me, if you merge my changes and additions first - and than apply some "revert-like commits"; if this is not to much work for you.

I just found out why "Travis-ci"-Tester failed!

The "Travis-ci"-Tester failed, the error message 

```
File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
 return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: near ")": syntax error
The command "./src/manage-test.py test accounts attestation checker configuration solutions tasks" exited with 1.
```

Searching after this error-message, I found this explanation

[http://stackoverflow.com/questions/37955984/trying-to-migrate-in-django-1-9-strange-sql-error-django-db-utils-operationa](http://stackoverflow.com/questions/37955984/trying-to-migrate-in-django-1-9-strange-sql-error-django-db-utils-operationa)

The solution is, that migration-files hat to be changed to get working with sqlite.
Here concrete it is in: `src/checker/migrations/0003_merge-hbrs.py` remove (or comment out)
all `RemoveField`-Operation for corresponding `DeleteModel`-Operations.

Again, how the problem arose:

1. The Praktomat standard version has been installed.
2. Some checkers have been disabled: `src/checker/checker/__init__.py`
3. After that a migration was generated, which deletes Models (= Tables) from the database , so that database and Django models are again "synchronous".
4. The creation of the migration has somehow failed for sqlite (but acceptable for pgsql), because
    a) In the migration first from different tables single Columns got deleted, 
    b) but then for these changes tables the entire table got deleted. i.e
```
        migrations.RemoveField(
            model_name='cbuilder',
            name='task',
        ),
        migrations.DeleteModel(
            name='CBuilder',
        )

```

That looks Strange. 

There it is a known django-bug, that "Removing a model's last field results in SQL syntax error" _strongly_ dependend on the used _database management system_ [https://code.djangoproject.com/ticket/24424](https://code.djangoproject.com/ticket/24424) - the solution for the sqlite-backend would be changing `django/db/backends/sqlite3/schema.py` on the travis-server like [https://github.com/django/django/pull/4325/files#diff-0c8f495bfee773ab7b5409533bd6d7efL142](https://github.com/django/django/pull/4325/files#diff-0c8f495bfee773ab7b5409533bd6d7efL142) shows.


Best regards,
Robert

**Comment by ifrh** [comment]
Hi Martin,
I have now done a "revert like" merge with your current master: see commit https://github.com/KITPraktomatTeam/Praktomat/pull/238/commits/de5ab7f67a1eb86e80f2ca54a8b223f6db81b592 
Now all the files should be identical with your current master.

I would like now start from this commit new branches - 
perhaps this time I should create for each feature one new branch.

1. make .gitmodules https_proxy compatible again (our server is behind a https_proxy)
2. "AutoAttestChecker"
3. "Dynamic upload waiting time for students"
4. "Praktomat - LDAP connection" (with dummy values for showing config)

**Comment by ifrh** [comment]
because in this branch after my "revert like" merge of current master branch there are no differences in files I close this pull-request. You don't need to merge it. But please keep it for reference at least until all above "reverted" features have their own pull request.
Best regard,
Robert

**Comment by ifrh** [comment]
Since March 2017 all H-BRS features and bugfixes have their own pull requests.
Best regards,
Robert

**Pull request closed without merging**
