### PR TITLE
Don't overwrite DJANGO_SETTINGS_MODULE

### PR DESCRIPTION
**Pull request by physikerwelt**
When deploying praktomat via git changes to the file
/src/settings/local.py might cause merge conflicts.
A possible solution to this is to configure
the settings file in the apache config. For instance
```
SetEnv DJANGO_SETTINGS_MODULE settings.local
```

See also #259

### CODE REVIEW

**Comment by ifrh** [comment]
Have you tried with your above changes to run multiple praktomat instances on the same server?

**Comment by physikerwelt** [comment]
> Have you tried with your above changes to run multiple praktomat instances on the same server?

Yes.

**Comment by ifrh** [comment]
> > Have you tried with your above changes to run multiple praktomat instances on the same server?
> 
> Yes.

If I found some information [1],[2], that by running the Django instances in separate processes there can be no possibility of environment variables leaking from one to the other. 
But from my understanding `WSGIScriptAlias` with parameter `process-group` inside `Macro Praktomat` ( https://github.com/KITPraktomatTeam/Praktomat/blob/master/documentation/apache_praktomat_wsgi.conf#L29 ) needs an uniq value for
separating differend django applications running on the same server.

We could change `WSGIScriptAlias /$id  $path/Praktomat/wsgi/praktomat.wsgi process-group=local` 
to i.e. `WSGIScriptAlias /$id  $path/Praktomat/wsgi/praktomat.wsgi process-group=local_$id`

And consequently `os.environ.setdefault('DJANGO_SETTINGS_MODULE...` in https://github.com/KITPraktomatTeam/Praktomat/blob/master/wsgi/praktomat.wsgi#L26 should get a small change too: That means read environment variable `mod_wsgi.process_group` and remove substring `$id` before storing it to environment variable `DJANGO_SETTINGS_MODULE`,

[1] http://blog.dscpl.com.au/2012/10/requests-running-in-wrong-django.html 
[2] https://gist.github.com/GrahamDumpleton/b380652b768e81a7f60c?permalink_comment_id=2970235#gistcomment-2970235

**Comment by ifrh** [comment]
> We could change `WSGIScriptAlias /$id $path/Praktomat/wsgi/praktomat.wsgi process-group=local` to i.e. `WSGIScriptAlias /$id $path/Praktomat/wsgi/praktomat.wsgi process-group=local_$id`
> 
> And consequently `os.environ.setdefault('DJANGO_SETTINGS_MODULE...` in https://github.com/KITPraktomatTeam/Praktomat/blob/master/wsgi/praktomat.wsgi#L26 should get a small change too: That means read environment variable `mod_wsgi.process_group` and remove substring `$id` before storing it to environment variable `DJANGO_SETTINGS_MODULE`,

I created the change and put it into repository via commit https://github.com/ifrh/Praktomat/commit/12182e76f0f6e0b223e8480e7f8f7531920acf65  which is part of and is part of pullrequest [Bugfix merge marathon feb2022 ... some more beside "Delete duplicate MOD_XSENDFILE_V1_0 setting" #320](https://github.com/KITPraktomatTeam/Praktomat/pull/320)

concrete parts are here 
- https://github.com/ifrh/Praktomat/commit/12182e76f0f6e0b223e8480e7f8f7531920acf65#diff-3b4baacde895cf2ef29bacfe376e44ea045ecdecf6b51e32a417c94ea71942f6R20 
- https://github.com/ifrh/Praktomat/commit/12182e76f0f6e0b223e8480e7f8f7531920acf65#diff-7b5d5f52cec25641ba9f79bd9cda4e6804a8dd95f18274d479faffa9f9e50253R26

**Comment by ifrh** [comment]
> > That means read environment variable `mod_wsgi.process_group` and remove substring `$id` before storing it to environment variable `DJANGO_SETTINGS_MODULE`,
> 
> I created the change and put it into repository via commit [ifrh@12182e7](https://github.com/ifrh/Praktomat/commit/12182e76f0f6e0b223e8480e7f8f7531920acf65)

With that commit I repair a bug resulting from a misunderstanding : DJANGO_SETTINGS_MODULE lives as environment variable, but mod_wsgi.process_group is not an environment variable.

**Pull request merged**
