### PR TITLE
Compiler C

### PR DESCRIPTION
**Pull request by andromeda979**
When we select the compiler we already know that it is a necessary
requirement. A program with an error does not compile.
That is why I have made this small modification so ‘Required’ is
automatically selected in the Compiler C.

I want to suggest to implement the regular expression:

“^[a-zA-Z0-9_ . -\?!]*.[cC]$”

As a possible side effect, the student that is used to other IDEs in
which the same solution do not represent a error source, e.g. Visual
studio, is discouraged to use Praktomat.

### CODE REVIEW

**Comment by ifrh** [comment]
Hi,
Well I think the value for _file_pattern in src/checker/compiler/Builder.py
should be as universal as for differend filesystems and differend programming-languages is possible. 
Only inside src/checker/compiler/CBuilder.py you should limit to ending *.c *.C files 

I don't get your point with MS Visual Studio. What do you mean there.

Best regards,
Robert

**Comment by StefanieScherzinger** [comment]
> I don't get your point with MS Visual Studio. What do you mean there.

We've been observing that about 10% of students upload solutions with whitespace or special characters (!, *, ?) in their file names.

Usually, IDEs like CodeBlocks and VisualStudio don't mind, but Praktomat won't manage to compile the file. Unfortunately, students did not get a helpful error message.
With students new to programming, this has been causing a lot of frustration.
They feel helpless, since their IDE has no problem with the solution,
and often they approach us, telling us that Praktomat is "broken".

Others have observed this issue as well:
https://github.com/KITPraktomatTeam/Praktomat/issues/224

By this simple change to the Regexp, we could effectively spare ourselves and the students a lot of frustration.

I think making the Regexp a bit more restrictive has also educational value,
since programmers really shouldn't be using special characters in their file names.

Best regards,
Stefanie

**Comment by mhecker** [comment]
This pull request now contains many changes that i would gladly merge (scala compiler, imrovements to TextChecker). Thank you very much for those.

I will now cherry-pick those changes, taking care that you can later merge KITPraktomatTeam/master cleanly into your master.

Other changes, though, in my opinion, would be better off in a local "reconfiguration-branch" that you could manage in your installation (especially, those changing defaults, such as 5c294cfa467026075f6d555d0d5c2dde4b58ed1b or the controversial d07f9c04add826fe606ee85cee181c6ca40b8f4b).

**Comment by mhecker** [comment]
I've now done as announced above, see commits
09814d9135f4aa0db06ec0ada7acab106a958b0a to e2c766d09b826d4f1f81bb690d773fae6d01e017 on master.

You might be interested in the small improvements i made to the scala builder.

**Comment by ifrh** [comment]
@andromeda979 @StefanieScherzinger Have you implemented a CUnit-Checker or a CppUnit-Checker for your Praktomat? 

https://sourceforge.net/p/cunit/    

https://sourceforge.net/projects/cppunit/ 

Or how are you doing your C / Cpp Unit-Tests inside Praktomat?

**Comment by ifrh** [comment]
I created a pullrequest for our C/C++ UnitCheckers, see #298

**Pull request closed without merging**
